### ISSUE TITLE
About NMS

### ISSUE THREAD

**Issue by komejisatori** [zzzxxxttt/pytorch_simple_CenterNet_47#1]
Thanks for your simpler implementation! However, I noticed that the nms is used when testing. But the official report said that nms is unnecessary when we use onle one image scale. So I want to know whether your code is different from the official one? Will the nms affect detection results when test scale is 1?

**Comment by zzzxxxttt** [comment]
Hi @komejisatori 
My implementation is the same as the official code, NMS is always useful since the flip test is used.

**Comment by komejisatori** [comment]
Thanks for your reply. If I turn off flip_test, can I skip nms? 
By the way, another version of yours has DCN module, which one performs better?

**Comment by zzzxxxttt** [comment]
I have not tried turn off nms, I guess the performance will drop a little. 
The DCN used in another repo is for ResDCN backbone, not for Hourglass.

**Comment by komejisatori** [comment]
@zzzxxxttt Thanks very much! I managed to train for my own dataset using large_hourglass. However, I found it a little bit slow. Maybe 5 hours / epoch under input size of 512 (about 100k images). Is this speed normal?

**Comment by zzzxxxttt** [comment]
The speed depends on your GPU, it's about 1.5 h/epoch on 8xV100 GPUs.
