### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by BuiNgocHai** [zzzxxxttt/pytorch_simple_CenterNet_47#3]
if i want to inference a single image and show the results on the image,how can I achieve it quickly?I would appreciate it if you can share the inference code.thank u

**Comment by zzzxxxttt** [comment]
There is a demo.py in my [CenterNet-45 repo](https://github.com/zzzxxxttt/pytorch_simple_CenterNet_45/blob/master/demo.py), you could use it as a reference.
