### ISSUE TITLE
How to visualize heatmap of output and input 

### ISSUE THREAD

**Issue by BuiNgocHai** [zzzxxxttt/pytorch_simple_CenterNet_47#5]
I'm trying to visualize output heat map from model. where can i start from

**Comment by zzzxxxttt** [comment]
You can sum the output featuremap over channel axis, then plot it using matplotlib.

**Comment by BuiNgocHai** [comment]
hmm i know that output has 8 variables:
1st, 2nd and 3rd of size [batchsize, class, 128, 128] --> these are the predicted heatmaps for top left, bottom right and center keypoints.  
I try to visulize them but i see all value has negative

**Comment by zzzxxxttt** [comment]
Just apply the sigmoid function on heatmaps to obtain the class probability.

**Comment by BuiNgocHai** [comment]
I got it. Thanks you
